// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package repository

import (
	"database/sql"

	"github.com/google/uuid"
)

type BbqDevice struct {
	ID       uuid.UUID `json:"id"`
	Name     string    `json:"name"`
	Location string    `json:"location"`
}

type BbqSensor struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
}

type BbqSensorReading struct {
	ID              uuid.UUID `json:"id"`
	SessionID       uuid.UUID `json:"session_id"`
	SensorID        uuid.UUID `json:"sensor_id"`
	ProbeNumber     int32     `json:"probe_number"`
	Temperature     float64   `json:"temperature"`
	ReadingOccurred int64     `json:"reading_occurred"`
}

type BbqSession struct {
	ID           uuid.UUID     `json:"id"`
	DeviceID     uuid.UUID     `json:"device_id"`
	DesiredState uuid.UUID     `json:"desired_state"`
	Description  uuid.UUID     `json:"description"`
	StartTime    int64         `json:"start_time"`
	EndTime      sql.NullInt64 `json:"end_time"`
}

type BbqSubject struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
}

type BbqSubjectState struct {
	ID          uuid.UUID `json:"id"`
	SubjectID   uuid.UUID `json:"subject_id"`
	State       string    `json:"state"`
	Temperature int32     `json:"temperature"`
}
