export const ORDERS_CREATE_CART = "ORDERS_CREATE_CART";
export const ORDERS_ADD_ITEM = "ORDERS_ADD_ITEM";
export const ORDERS_CHECKOUT_CART = "ORDERS_CHECKOUT_CART";
export const ORDERS_LOAD_ORDER = "ORDERS_LOAD_ORDER";
export const PRODUCTS_LOADED = "PRODUCTS_LOADED";
export const PRODUCTS_LOADING = "PRODUCTS_LOADING";
