// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=js+dts"
// @generated from file bbq/collector/v1/collector_service.proto (package bbq.collector.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { RecordRequest, RecordResponse, SessionRequest, SessionResponse } from "./collector_service_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service bbq.collector.v1.CollectorService
 */
export const CollectorService = {
  typeName: "bbq.collector.v1.CollectorService",
  methods: {
    /**
     * @generated from rpc bbq.collector.v1.CollectorService.Record
     */
    record: {
      name: "Record",
      I: RecordRequest,
      O: RecordResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bbq.collector.v1.CollectorService.Session
     */
    session: {
      name: "Session",
      I: SessionRequest,
      O: SessionResponse,
      kind: MethodKind.Unary,
    },
  }
};

