// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=js+dts"
// @generated from file bbq/collector/v1/collector_service.proto (package bbq.collector.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { RecordRequest, RecordResponse, SessionRequest, SessionResponse } from "./collector_service_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service bbq.collector.v1.CollectorService
 */
export declare const CollectorService: {
  readonly typeName: "bbq.collector.v1.CollectorService",
  readonly methods: {
    /**
     * @generated from rpc bbq.collector.v1.CollectorService.Record
     */
    readonly record: {
      readonly name: "Record",
      readonly I: typeof RecordRequest,
      readonly O: typeof RecordResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bbq.collector.v1.CollectorService.Session
     */
    readonly session: {
      readonly name: "Session",
      readonly I: typeof SessionRequest,
      readonly O: typeof SessionResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

