// @generated by protoc-gen-es v1.9.0 with parameter "target=js+dts"
// @generated from file bbq/intake/v1/bbq.proto (package bbq.intake.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message bbq.intake.v1.Sensor
 */
export const Sensor = /*@__PURE__*/ proto3.makeMessageType(
  "bbq.intake.v1.Sensor",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "manufacturer", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "sensor_count", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "temperature_unit", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "sensor_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message bbq.intake.v1.SensorReading
 */
export const SensorReading = /*@__PURE__*/ proto3.makeMessageType(
  "bbq.intake.v1.SensorReading",
  () => [
    { no: 1, name: "sensor_number", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "temperature", kind: "scalar", T: 2 /* ScalarType.FLOAT */ },
  ],
);

/**
 * @generated from message bbq.intake.v1.Reading
 */
export const Reading = /*@__PURE__*/ proto3.makeMessageType(
  "bbq.intake.v1.Reading",
  () => [
    { no: 1, name: "session_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "readings", kind: "message", T: SensorReading, repeated: true },
    { no: 3, name: "recorded_at", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ],
);

/**
 * @generated from message bbq.intake.v1.SessionDataRate
 */
export const SessionDataRate = /*@__PURE__*/ proto3.makeMessageType(
  "bbq.intake.v1.SessionDataRate",
  () => [
    { no: 1, name: "sensors", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "max_readings_minute", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message bbq.intake.v1.Session
 */
export const Session = /*@__PURE__*/ proto3.makeMessageType(
  "bbq.intake.v1.Session",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "device_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "desired_state", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "start_time", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 6, name: "end_time", kind: "scalar", T: 3 /* ScalarType.INT64 */, opt: true },
    { no: 7, name: "sensor_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "session_type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 9, name: "subject_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

