// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=js+dts"
// @generated from file bbq/intake/v1/intake_service.proto (package bbq.intake.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { RecordRequest, RecordResponse, SessionRequest, SessionResponse } from "./intake_service_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service bbq.intake.v1.IntakeService
 */
export declare const IntakeService: {
  readonly typeName: "bbq.intake.v1.IntakeService",
  readonly methods: {
    /**
     * @generated from rpc bbq.intake.v1.IntakeService.Record
     */
    readonly record: {
      readonly name: "Record",
      readonly I: typeof RecordRequest,
      readonly O: typeof RecordResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bbq.intake.v1.IntakeService.Session
     */
    readonly session: {
      readonly name: "Session",
      readonly I: typeof SessionRequest,
      readonly O: typeof SessionResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

