export const BBQ_SESSIONS_LOADED = "BBQ_SESSIONS_LOADED";
export const BBQ_DEVICES_LOADED = "BBQ_DEVICES_LOADED";
export const BBQ_MONITORS_LOADED = "BBQ_MONITORS_LOADED";
export const ERROR_OCCURRED = "ERROR_OCCURRED";