apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: bbq-frontend
  name: bbq-frontend
  selfLink: /api/v1/namespaces/default/services/bbq-frontend
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: bbq-frontend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: bbq-frontend
spec:
  template:
    metadata:
      labels:
        app: bbq-frontend
    spec:
      containers:
        - name: bbq-frontend
          image: myfamilycooks.azurecr.io/bbq/frontend:0.0.2
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: myfamilycooks
