apiVersion: v1
data:
  postgresql-server: 192.168.20.11
  redis-one: bbq-cache-redis-master.default.svc.cluster.local:6379
  redis-two: bbq-cache-redis-master.default.svc.cluster.local:6379
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: bbq-config
  selfLink: /api/v1/namespaces/default/configmaps/bbq-config
