apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"creationTimestamp":"2019-02-04T14:13:48Z","labels":{"app":"go-bbq"},"name":"go-bbq","namespace":"default","resourceVersion":"153408","selfLink":"/api/v1/namespaces/default/services/go-bbq","uid":"16df4ceb-2887-11e9-a976-00155d0a013b"},"spec":{"clusterIP":"10.105.11.237","externalTrafficPolicy":"Cluster","ports":[{"port":80,"protocol":"TCP","targetPort":21337}],"selector":{"app":"go-bbq"},"sessionAffinity":"None","type":"NodePort"}}
  creationTimestamp: null
  labels:
    app: go-bbq
  name: go-bbq
  selfLink: /api/v1/namespaces/default/services/go-bbq
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 80
    protocol: TCP
    targetPort: 21337
  selector:
    app: go-bbq
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
