name: Go
on: 
  push:
    paths: ["baste/**/*.go"]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.0
        cache: true
        cache-dependency-path: baste/go.sum